### ISSUE TITLE
Does not detect CPU yet? (AMD 5800x or all CPUs?)

### ISSUE THREAD

**Issue by alexandreracine** [GameTechDev/PresentMon#140]
FINAL Edit! This is now fixed, on version 0.6 beta, released at the start of November 2023.
Get the latest version on the page : https://game.intel.com/story/intel-presentmon/
CPU name, CPU utilization, and CPU Frequency are now working. See picture below. I'll create a new one for the temperature and power limit ;)

![image](https://github.com/GameTechDev/PresentMon/assets/5158041/eca79ef1-0731-4729-984f-3db6d05c9dd7)

Edit : **Official answer from Intel** (user markgalvan-intel) DR;tl : **They are working on it**. No ETA.

I'll keep this issue open until it is resolved, and post the solution. The solution will probably be a future version of Intel PresentMon. I'll post the version when available.

---------------------------

I don't know if this is AMD related, or just if CPU is not yet implemented?

CPU Utilization (Avg) and CPU Temperature (Avg) are in a NA state.

I can get these values with other software like HWinfo ...

Seems promising!

Edit : ~~If you have an Intel processor, and this works or not, please comment below!~~
Edit2 : **Official answer from Intel** (user markgalvan-intel)  : "At the current time Intel PresentMon does not yet support gathering comprehensive CPU telemetry. We're actively considering our next steps in this regard." below here https://github.com/GameTechDev/PresentMon/issues/140#issuecomment-1688492425

Edit 3 : The problem is described here below in this comment : https://github.com/GameTechDev/PresentMon/issues/140#issuecomment-1703908844 and the answer here : https://github.com/GameTechDev/PresentMon/issues/140#issuecomment-1706732434

**Comment by Serverfrog** [comment]
Same with an AMD Ryzen 9 7950X

**Comment by Wroyk** [comment]
My i7-4770K is also not being recognized.
HWinfo and HWMonitor show the values

![grafik](https://github.com/GameTechDev/PresentMon/assets/29730585/efefe118-da0a-4f7c-b980-943eeb717b77)
![grafik](https://github.com/GameTechDev/PresentMon/assets/29730585/c1ba6778-b193-402a-8b5b-2ab130953e3e)

**Comment by YeahBobi** [comment]
Same happens with AMD Ryzen 7 7800X3D. The software shows only "NA" as a value.

**Comment by FAChenier** [comment]
Same here with 5900X. Same as Wroyk, HWiNFO gets all of the data correctly. Interesting that it also doesn't work for an intel CPU as mentioned above so maybe it's just broken as of now?

**Comment by heyflo** [comment]
Same here with the 13700K

**Comment by cichy45** [comment]
The same issue is present with my old Ryzen 1600 + B350 Motherboard - the readout is simply N/A for Clock/Power/Utilization (the three I checked). 
HWiNFO64 can read CPU sensors as Clock/Power/Usage correctly.

**Comment by markgalvan-intel** [comment]
Hello!

At the current time Intel PresentMon does not yet support gathering comprehensive CPU telemetry. We're actively considering our next steps in this regard.

That being said, we are using WMI to gather the CPU Name, CPU Utilization and CPU Frequency. This must be failing for some reason. Are folks seeing this on Windows 11 or Windows 10?

We'll dive into this more and try to reproduce.

**Comment by cichy45** [comment]
@markgalvan-intel 
I use Windows 10. Is there anything I can do to help you troubleshoot?

**Comment by FAChenier** [comment]
> Hello!
> 
> At the current time Intel PresentMon does not yet support gathering comprehensive CPU telemetry. We're actively considering our next steps in this regard.
> 
> That being said, we are using WMI to gather the CPU Name, CPU Utilization and CPU Frequency. This must be failing for some reason. Are folks seeing this on Windows 11 or Windows 10?
> 
> We'll dive into this more and try to reproduce.

Windows 11 up to date as of 2023-08-22, none of the CPU telemetry is functional under any situation (restart, idle, gameplay, ...)

**Comment by heyflo** [comment]
> Hello!
> 
> At the current time Intel PresentMon does not yet support gathering comprehensive CPU telemetry. We're actively considering our next steps in this regard.
> 
> That being said, we are using WMI to gather the CPU Name, CPU Utilization and CPU Frequency. This must be failing for some reason. Are folks seeing this on Windows 11 or Windows 10?
> 
> We'll dive into this more and try to reproduce.

Thanks for clarifying! I'm using Windows 11 up to date.

**Comment by markgalvan-intel** [comment]
I have been trying to reproduce this issue but not having any luck. 

Couple of quick questions to help narrow down the potential issue:
1. Is the CPU NAME coming back as "UNKNOWN_CPU" for everyone?
2. In a command prompt does the command "typeperf.exe "\Processor Information(_Total)\% Processor Performance" return back data successfully?

Thanks!!

**Comment by alexandreracine** [comment]
Q1 : yes
Q2 : The answer is :"z patienter... Erreur : aucun compteur valide."

that translate to "Error no valid counter"

That's with an admin prompt, but also with a user prompt.

![image](https://github.com/GameTechDev/PresentMon/assets/5158041/226e098f-b80f-458c-94b5-c1ce3b05a9d9)

**Comment by markgalvan-intel** [comment]
Whoops! I had a typo in the command I sent. My apologies!

When you have a chance could you try the following command in a administrator command prompt:
typeperf.exe "\Processor Information(_Total)\% Processor Performance"

The last time I sent the command I missed the "\" in front of the "%"

Again, sorry for the confusion.

**Comment by alexandreracine** [comment]
> Whoops! I had a typo in the command I sent. My apologies!
> 
> When you have a chance could you try the following command in a administrator command prompt: typeperf.exe "\Processor Information(_Total)% Processor Performance"
> 
> The last time I sent the command I missed the "" in front of the "%"
> 
> Again, sorry for the confusion.

The command does not work, but I think I found out the problem ;) and a potential solution for the devs.

My Windows 10 is in French.

So If I use "typeperf -qx" to list all performance counters, I get a list like this:

`
...
\Informations sur le processeur(_Total)\Pourcentage de rendement du processeur
\Informations sur le processeur(0,0)\Pourcentage de performances du processeur
\Informations sur le processeur(0,1)\Pourcentage de performances du processeur
\Informations sur le processeur(0,10)\Pourcentage de performances du processeur
\Informations sur le processeur(0,11)\Pourcentage de performances du processeur
\Informations sur le processeur(0,12)\Pourcentage de performances du processeur
...
`

So if I use >typeperf "\Informations sur le processeur(_Total)\Pourcentage de rendement du processeur"

I get, probably what you are seeking:

`
"(PDH-CSV 4.0)","\\ROUGE\Informations sur le processeur(_Total)\Pourcentage de rendement du processeur"
"09/02/2023 14:26:20.667","1.306871"
"09/02/2023 14:26:21.674","1.470899"
"09/02/2023 14:26:22.685","1.409267"
...
`

The Author of HWiNFO commented on how they pull data from the chips, and the summary is that because of the lack of unified standards, they customize everything.

Reference here https://www.hwinfo.com/forum/threads/how-does-hwinfo-app-gather-info-from-computers.2880/

A solution is to use the counters numbers/ID instead of the names/descriptors, but the numbers will change from Windows to Windows even if they have the same local/language. So the solution is to create a custom table, with the correct numbers associated to each counter that are listed in Intel PresentMon.

Someone already made that :) Reference and a script here https://www.zabbix.com/forum/zabbix-cookbook/7524-how-to-force-perfmon-counters-description-to-be-in-english

The Pandora box is now open! :)

**Comment by MTstomachTM** [comment]
> I have been trying to reproduce this issue but not having any luck.
> 
> Couple of quick questions to help narrow down the potential issue:
> 
> 1. Is the CPU NAME coming back as "UNKNOWN_CPU" for everyone?
> 2. In a command prompt does the command "typeperf.exe "\Processor Information(_Total)% Processor Performance" return back data successfully?
> 
> Thanks!!

1. Mine came back as expected. CPU is AMD Ryzen 7 5800X3D
2. Command ```typeperf.exe "\Processor Information(_Total)\% Processor Performance"``` is returning data as expected

All observed on Windows 11 Home build 22621.2134

But Intel PresentMon widget (the overlay) can only present CPU utilization and frequency. Other widgets showing NA.

**Comment by markgalvan-intel** [comment]
Hello @MTstomachTM, Thank you very much for the response. At the current time Intel PresentMon only returns back the utilization and frequency data. We're still considering our next steps in what data we are going to return back with regards to the CPU.

**Comment by DangerousDetlef** [comment]
> I have been trying to reproduce this issue but not having any luck.
> 
> Couple of quick questions to help narrow down the potential issue:
> 
>     1. Is the CPU NAME coming back as "UNKNOWN_CPU" for everyone?
> 
>     2. In a command prompt does the command "typeperf.exe "\Processor Information(_Total)% Processor Performance" return back data successfully?
> 
> 
> Thanks!!

Hey, I'm on Windows 11 with an i9-9900K and get everything "NA" which has to do with CPU information. I typed in the command and got the same error others got: "Error: No valid performance indicators".

![grafik](https://github.com/GameTechDev/PresentMon/assets/5159043/87d23225-fef0-4d7c-a354-f7d8c86f4c13)
![grafik](https://github.com/GameTechDev/PresentMon/assets/5159043/aa37bb27-8d86-4414-8e9a-b6b34318cd1f)

**Comment by alexandreracine** [comment]
@DangerousDetlef 

You can look at my post up here https://github.com/GameTechDev/PresentMon/issues/140#issuecomment-1703908844 
... that shows how to get the correct performance counter name since your system is not in English.

The dev working on that aspect are aware, and are looking at what the next steps are.
Have a great day!

**Comment by DangerousDetlef** [comment]
> @DangerousDetlef
> 
> You can look at my post up here [#140 (comment)](https://github.com/GameTechDev/PresentMon/issues/140#issuecomment-1703908844) ... that shows how to get the correct performance counter name since your system is not in English.
> 
> The dev working on that aspect are aware, and are looking at what the next steps are. Have a great day!

I tried to find out the German version of that command but seems to be not that simple. Is this information needed any longer? Or does it just seem like that there's a problem with pulling the CPU info because of language problem?

**Comment by alexandreracine** [comment]
@DangerousDetlef , the information is not needed anymore, Intel has the data and will look it up. If needed "markgalvan-intel" will tag you in a message. I have updated the original post issue to reflect that. Thanks.

**Comment by icavalheiro** [comment]
Can confirm this is also happening on Win10 in Brazilian Portuguese.

**Comment by tehpingwin** [comment]
I have an i7-6950x and it also shows as unknown_cpu

**Comment by alexandreracine** [comment]
FINAL Edit! This is now fixed, on version 0.6 beta, released at the start of November 2023.
Get the latest version on the page : https://game.intel.com/story/intel-presentmon/
CPU name, CPU utilization, and CPU Frequency are now working. See picture at the start of the post.
I'll create a new one for the temperature and power limit ;)

**Comment by Maximus-CZ** [comment]
CPU stuff still not working in 0.6 Beta
![image](https://github.com/GameTechDev/PresentMon/assets/5832592/1048656a-4282-4d69-bdb4-5654bfed9247)
Using 0.6 Beta, 7800x3d, win 10. GPU stuff works

**Comment by RodroG-85** [comment]
@alexandreracine I'm using PresentMon 2.0.0, and in my case, the issue is that the PresentMon CPU Frequency metric readings don't match any HWInfo64 CPU clock/frequency readings. I tried raw, avg., and max, with the same result (no match). However, the PresentMon CPU Utilization metric readings match HWiNFO64 values pretty well.

Have you any idea why it's happening? Please could you look into it?

I'm using an Intel Core 12th Gen i9-12900K.

**Comment by alexandreracine** [comment]
> @alexandreracine I'm using PresentMon 2.0.0, and in my case, the issue is that the PresentMon CPU Frequency metric readings don't match any HWInfo64 CPU clock/frequency readings. I tried raw, avg., and max, with the same result (no match). However, the PresentMon CPU Utilization metric readings match HWiNFO64 values pretty well.
> 
> Have you any idea why it's happening? Please could you look into it?
> 
> I'm using an Intel Core 12th Gen i9-12900K.

You'll have to start a new issue for that. Have a great day.

**Comment by RodroG-85** [comment]
@alexandreracine Sorry, it was my bad. I rechecked, and PresentMon 2.0 CPU Frequency and CPU Utilization metrics would match quite well (the marginal reading differences seem all within the margin of error). I hadn't looked carefully enough.

Here is a screenshot that shows them matching (avg. values):

<img width="960" alt="CPUfrequency-PresentMon2 0-HWiNFO64" src="https://github.com/GameTechDev/PresentMon/assets/56508839/710ce336-8ab7-4cae-ad8d-99f3b6a9bb11">

I have only a doubt. Are the outlined HWiNFO64 sensor metrics the references I have to look for CPU Frequency and CPU Utilization comparisons?

By the way, keep up the great work! The app is great for benchmarking purposes and monitoring performance. :)
